### ISSUE TITLE
Doesn't work on Gnome-Terminal

### ISSUE THREAD

**Issue by MeanEYE** [metalelf0/gnome-terminal-colors#5]
After running `./install.sh` and selecting color theme I get this:

```
Please select a Gnome Terminal profile:

You have selected:

  Scheme:  gruvbox-dark
Failed to get value for `/apps/gnome-terminal/profiles//visible_name': Bad key or directory name: "/apps/gnome-terminal/profiles//visible_name": Can't have two slashes '/' in a row
  Profile: is not a valid profile ()

Are you sure you want to overwrite the selected profile?
(YES to continue) 
```
After confirming script give success message but colors are not applied.
Gnome-Terminal version is 3.22.1

**Comment by stevenleeg** [comment]
I'm seeing the same issue on gnome terminal

**Comment by MeanEYE** [comment]
Issue is solved upstream. I cloned upstream and symlinked individual
directories in colors. Upstream script works as expected with colors from
this one.

**Comment by stevenleeg** [comment]
Yep, looks like that did it!

For anyone else seeing this in the future, I checked out [the upstream repo](https://github.com/Anthony25/gnome-terminal-colors-solarized), copied all of the directories under `colors` in this repo into `colors` of that repo, and then ran the script normally.

:beers:

**Comment by bl4ck5un** [comment]
+1

**Comment by metalelf0** [comment]
Ok, I've seen this issue. Will need some time to rebase my repo onto the upstream master. If anybody has some spare time and wants to do this (and submit a PR) you're welcome, otherwise I'll do it in the next days. Thanks for reporting the issue :)

**Comment by metalelf0** [comment]
@bl4ck5un @stevenleeg @MeanEYE hi all, I merged my changes manually on top of upstream/master and pushed the result on a branch called `upstream_master` on this repo. I don't have access to a gnome install at the moment, so could you please check it out and see if it works? I'll merge it on my master right after. Thanks for your help!

**Comment by ninrod** [comment]
@metalelf0, I had this issue and just tested your branch, it worked like a charm.

**Comment by metalelf0** [comment]
@ninrod thanks a lot, merging it now! 👍
